import { reactive } from "vue";

export const store = reactive({
  selectedCategory: "",
  categoriesInfos: [
    {
      imgPath: "./src/assets/img/cat_1-1540x750.jpg",
      title: "Software Development",
      doubleCourse: false,
      courses: 3,
    },
    {
      imgPath: "./src/assets/img/cat_2-740x310.jpg",
      title: "Art",
      imgPath2: "./src/assets/img/cat_3-740x310.jpg",
      title2: "Material Design",
      doubleCourse: true,
      courses: 2,
      courses2: 5,
    },
    {
      imgPath: "./src/assets/img/cat_4-740x310.jpg",
      title: "Exercise",
      doubleCourse: false,
      courses: 7,
    },
    {
      imgPath: "./src/assets/img/cat_5-740x310.jpg",
      title: "Music",
      doubleCourse: false,
      courses: 3,
    },
    {
      imgPath: "./src/assets/img/cat_6-740x310.jpg",
      title: "Photography",
      doubleCourse: false,
      courses: 4,
    },
  ],
  coursesInfos: [
    {
      imgPath: "./src/assets/img/c_1-software-development.png",
      title: "Web Coding and Apache Basics theory",
      category: "Software Development",
      average_vote: 5,
      price: "Free",
      tag: "Hot",
    },
    {
      imgPath: "./src/assets/img/c_2-software-development.jpeg",
      title: "Engine Creating on Unity from PRO",
      category: "Software Development",
      average_vote: 0,
      price: "€99,99",
      sale: "€49,99",
    },
    {
      imgPath: "./src/assets/img/c_3-software-development.jpeg",
      title: "Console Development Basics with Unity",
      category: "Software Development",
      average_vote: 4,
      price: "€79,99",
      sale: "€39,99",
      tag: "New",
    },

    {
      imgPath: "./src/assets/img/c_1-art.jpg",
      title: "Interior design concepts Masterclass",
      category: "Art",
      average_vote: 4,
      price: "Free",
      tag: "New",
    },
    {
      imgPath: "./src/assets/img/c_2-art.png",
      title: "Let`s paint Van Gogh`s Starry Night",
      category: "Art",
      average_vote: 0,
      price: "Free",
    },

    {
      imgPath: "./src/assets/img/c_1-material-design.png",
      title: "Basics of MasterStudy",
      category: "Material Design",
      average_vote: 5,
      price: "Free",
      tag: "Special",
    },
    {
      imgPath: "./src/assets/img/c_2-material-design.png",
      title: "Vector Design Basics Masterclass",
      category: "Material Design",
      average_vote: 5,
      price: "€89,99",
      sale: "€79,99",
    },
    {
      imgPath: "./src/assets/img/c_3-material-design.png",
      title: "How to Design Components Right",
      category: "Material Design",
      average_vote: 3,
      price: "Free",
    },
    {
      imgPath: "./src/assets/img/c_4-material-design.png",
      title: "Minimalism, How to make things simpler",
      category: "Material Design",
      average_vote: 0,
      price: "€79,99",
      tag: "Hot",
    },
    {
      imgPath: "./src/assets/img/c_5-material-design.png",
      title: "Choosing Filament Color for Concept",
      category: "Material Design",
      average_vote: 4,
      price: "€19,99",
      sale: "€9,99",
    },

    {
      imgPath: "./src/assets/img/c_1-exercise.jpeg",
      title: "Road Bike Manual or How to Be a Champion",
      category: "Exercise",
      average_vote: 4,
      price: "€19,99",
      sale: "€9,99",
    },
    {
      imgPath: "./src/assets/img/c_2-exercise.png",
      title: "Weight Training Courses with Any Di",
      category: "Exercise",
      average_vote: 0,
      price: "€64,99",
      tag: "New",
    },
    {
      imgPath: "./src/assets/img/c_3-exercise.png",
      title: "Swimming Sport Tricks for Beginner",
      category: "Exercise",
      average_vote: 2,
      price: "€49,99",
      sale: "€25,99",
    },
    {
      imgPath: "./src/assets/img/c_4-exercise.png",
      title: "Skiing basic Instruction and Videos",
      category: "Exercise",
      average_vote: 4,
      price: "€46,99",
      sale: "€36,99",
    },
    {
      imgPath: "./src/assets/img/c_5-exercise.jpg",
      title: "Run Forest, Run! How to create Running Route",
      category: "Exercise",
      average_vote: 0,
      price: "€63,99",
    },
    {
      imgPath: "./src/assets/img/c_6-exercise.png",
      title: "Success Bodybuilding with Protein Nutrition",
      category: "Exercise",
      average_vote: 0,
      price: "€67,99",
      sale: "€38,99",
      tag: "New",
    },
    {
      imgPath: "./src/assets/img/c_7-exercise.jpg",
      title: "Fitness Blender 15 Minute Fast Workout",
      category: "Exercise",
      average_vote: 0,
      price: "Free",
      tag: "New",
    },

    {
      imgPath: "./src/assets/img/c_1-music.jpeg",
      title: "How to be a DJ? Make Electronic Music",
      category: "Music",
      average_vote: 5,
      price: "Free",
      tag: "Hot",
    },
    {
      imgPath: "./src/assets/img/c_2-music.jpg",
      title: "Learning Jazz like in San Francisco",
      category: "Music",
      average_vote: 5,
      price: "€69,99",
      sale: "€39,99",
      tag: "Special",
    },
    {
      imgPath: "./src/assets/img/c_3-music.png",
      title: "Music Theory basics for beginners",
      category: "Music",
      average_vote: 4,
      price: "€59.99",
    },

    {
      imgPath: "./src/assets/img/c_1-photography.png",
      title: "How to get comfortable on camera",
      category: "Photography",
      average_vote: 3,
      price: "€59.99",
      sale: "€39.99",
    },
    {
      imgPath: "./src/assets/img/c_2-photography.jpg",
      title: "Fashion Photography from professional",
      category: "Photography",
      average_vote: 4,
      price: "Free",
    },
    {
      imgPath: "./src/assets/img/c_3-photography.jpg",
      title: "How to Make Beautiful Landscape photos?",
      category: "Photography",
      average_vote: 3,
      price: "€59.99",
      sale: "€39.99",
      tag: "Hot",
    },
    {
      imgPath: "./src/assets/img/c_4-photography.png",
      title: "Correct and Beautiful Design Interaction",
      category: "Photography",
      average_vote: 0,
      price: "€89.99",
      sale: "€79.99",
    },
  ],
});
